export const models = [
  {
    name: "GPT-3.5-turbo",
    value: "gpt-3.5-turbo",
    brand: "openai",
    icon: null,
    speed: 150,
    max_context_window: 4096,
    model_size: 20,
    mmlu_score: 70,
    mt_bench_score: 7.94,
    big_bench_score: 25,
    input_cost: 0.5,
    output_cost: 0.1,
    rate_limit: 30000,
    multilingual: 1,
    streaming_support: 1,
    function_call: 1,
    weight: 1,
  },
  {
    name: "GPT-3.5-turbo-16k",
    value: "gpt-3.5-turbo-16k",
    brand: "openai",
    icon: null,
    speed: 130,
    max_context_window: 16384,
    model_size: 20,
    mmlu_score: 70,
    mt_bench_score: 7.94,
    big_bench_score: 25,
    input_cost: 0.5,
    output_cost: 1,
    rate_limit: 30000,
    multilingual: 1,
    streaming_support: 1,
    function_call: 1,
    weight: 1,
    output_pricing: 0.002,
  },
  // {
  //   name: "GPT-4-32k",
  //   value: "gpt-4-32k",
  //   brand: "openai",
  //   icon: OpenAI,
  // },
  {
    name: "GPT-4",
    value: "gpt-4",
    brand: "openai",
    icon: null,
    speed: 14,
    max_context_window: 8192,
    model_size: 170,
    mmlu_score: 86.5,
    mt_bench_score: 8.99,
    big_bench_score: 40,
    input_cost: 30,
    output_cost: 60,
    rate_limit: 10000,
    multilingual: 1,
    streaming_support: 1,
    function_call: 1,
    weight: 1,
  },
  {
    name: "GPT-4-1106-preview",
    value: "gpt-4-1106-preview",
    brand: "openai",
    icon: null,
    speed: 70,
    max_context_window: 128000,
    model_size: 170,
    mmlu_score: 86.5,
    mt_bench_score: 8.99,
    big_bench_score: 40,
    input_cost: 10,
    output_cost: 30,
    rate_limit: 500,
    multilingual: 1,
    streaming_support: 1,
    function_call: 1,
    weight: 1,
  },
  {
    name: "Claude Instant 1.2",
    value: "claude-instant-1.2",
    brand: "anthropic",
    icon: null,
    speed: 150,
    max_context_window: 100000,
    model_size: 20,
    mmlu_score: 70,
    mt_bench_score: 7.85,
    big_bench_score: 20,
    input_cost: 1,
    output_cost: 2,
    rate_limit: 3500,
    multilingual: 1,
    streaming_support: 1,
    function_call: 1,
    weight: 1,
  },
  {
    name: "Claude 2.1",
    value: "claude-2.1",
    brand: "anthropic",
    icon: null,
    speed: 110,
    max_context_window: 200000,
    model_size: 20,
    mmlu_score: 78.5,
    mt_bench_score: 7.9,
    big_bench_score: 20,
    input_cost: 1.63,
    output_cost: 5.51,
    rate_limit: 3500,
    multilingual: 1,
    streaming_support: 1,
    function_call: 1,
    weight: 1,
  },
  {
    name: "Claude 2",
    value: "claude-2",
    brand: "anthropic",
    icon: null,
    speed: 110,
    max_context_window: 100000,
    model_size: 20,
    mmlu_score: 78.5,
    mt_bench_score: 7.9,
    big_bench_score: 20,
    input_cost: 11,
    output_cost: 33,
    rate_limit: 3500,
    multilingual: 1,
    streaming_support: 1,
    function_call: 1,
    weight: 1,
  },
  {
    name: "Claude Instant 1",
    value: "claude-instant-1",
    brand: "anthropic",
    icon: null,
    speed: 150,
    max_context_window: 100000,
    model_size: 20,
    mmlu_score: 70,
    mt_bench_score: 7.85,
    big_bench_score: 20,
    input_cost: 1,
    output_cost: 2,
    rate_limit: 3500,
    multilingual: 1,
    streaming_support: 1,
    function_call: 1,
    weight: 1,
  },
  {
    name: "Chat Bison",
    value: "chat-bison",
    brand: "google",
    icon: null,
    speed: 40,
    max_context_window: 8192,
    model_size: 540,
    mmlu_score: 60,
    mt_bench_score: 6.4,
    big_bench_score: 40,
    input_cost: 0.5,
    output_cost: 0.5,
    rate_limit: 90,
    multilingual: 1,
    streaming_support: 1,
    function_call: 0,
    weight: 1,
  },
  {
    name: "J2 Light",
    value: "j2-light",
    brand: "labs",
    icon: null,
    speed: 130,
    max_context_window: 8192,
    model_size: 178,
    mmlu_score: 60,
    mt_bench_score: 6.5,
    big_bench_score: 15,
    input_cost: 1,
    output_cost: 2,
    rate_limit: 500,
    multilingual: 1,
    streaming_support: 0,
    function_call: 0,
    weight: 1,
  },
  {
    name: "Command",
    value: "command",
    rate_limit: 500,
    speed: 150,
    brand: "cohere",
    icon: null,
    mmlu_score: null,
    mt_bench_score: null,
    big_bench_score: null,
    language_support: null,
    streaming_support: "Yes",
    input_pricing: null,
    output_pricing: null,
  },
  {
    name: "Command Light",
    value: "command-light",
    rate_limit: 500,
    speed: 150,
    brand: "cohere",
    icon: null,
    mmlu_score: null,
    mt_bench_score: null,
    big_bench_score: null,
    language_support: null,
    streaming_support: "Yes",
    input_pricing: null,
    output_pricing: null,
  },
  {
    name: "J2 Mid",
    value: "j2-mid",
    brand: "labs",
    icon: null,
    speed: 65,
    max_context_window: 8192,
    model_size: 178,
    mmlu_score: 60,
    mt_bench_score: 6.5,
    big_bench_score: 15,
    input_cost: 1,
    output_cost: 2,
    rate_limit: 500,
    multilingual: 1,
    streaming_support: 0,
    function_call: 0,
    weight: 1,
  },
  {
    name: "J2 Ultra",
    value: "j2-ultra",
    icon: null,
    brand: "labs",
    speed: 40,
    max_context_window: 8192,
    model_size: 178,
    mmlu_score: 60,
    mt_bench_score: 6.5,
    big_bench_score: 15,
    input_cost: 1,
    output_cost: 2,
    rate_limit: 500,
    multilingual: 1,
    streaming_support: 0,
    function_call: 0,
    weight: 1,
  },
  {
    name: "Gemini Pro",
    value: "gemini/gemini-pro",
    brand: "google",
    icon: null,
    speed: 10,
    max_context_window: 32000,
    model_size: 540,
    mmlu_score: 79.13,
    mt_bench_score: 6.8,
    input_cost: 1.3,
    output_cost: 2.6,
    rate_limit: 60,
    multilingual: 1,
    streaming_support: 1,
    function_call: 0,
    weight: 1,
  },
  {
    name: "Gemini Pro (Vertex AI)",
    value: "gemini-pro",
    brand: "google",
    icon: null,
    speed: 10,
    max_context_window: 32000,
    model_size: 540,
    mmlu_score: 79.13,
    mt_bench_score: 6.8,
    input_cost: 1.3,
    output_cost: 2.6,
    rate_limit: 60,
    multilingual: 1,
    streaming_support: 1,
    function_call: 0,
    weight: 1,
  },
  {
    name: "Mistral Tiny",
    value: "mistral/mistral-tiny",
    brand: "google",
    icon: null,
    speed: 250,
    max_context_window: 32000,
    model_size: 7,
    mmlu_score: 63,
    mt_bench_score: 7.61,
    big_bench_score: 20,
    input_cost: 0.15,
    output_cost: 0.4,
    rate_limit: 120,
    multilingual: 1,
    streaming_support: 1,
    function_call: 1,
    weight: 1,
  },
  {
    name: "Mistral Small",
    value: "mistral/mistral-small",
    brand: "google",
    icon: null,
    speed: 220,
    max_context_window: 32000,
    model_size: 56,
    mmlu_score: 70.6,
    mt_bench_score: 8.3,
    big_bench_score: 20,
    input_cost: 0.68,
    output_cost: 2,
    rate_limit: 120,
    multilingual: 1,
    streaming_support: 1,
    function_call: 1,
    weight: 1,
  },
  {
    name: "Mistral Medium",
    value: "mistral/mistral-medium",
    brand: "google",
    icon: null,
    speed: 250,
    max_context_window: 32000,
    model_size: 70,
    mmlu_score: 75.3,
    mt_bench_score: 8.61,
    big_bench_score: 20,
    input_cost: 2.8,
    output_cost: 8,
    rate_limit: 120,
    multilingual: 1,
    streaming_support: 1,
    function_call: 1,
    weight: 1,
  },
  {
    name: "GPT-4 (Azure)",
    value: "azure/gpt-4",
    brand: "azure",
    icon: null,
    speed: 48,
    max_context_window: 8192,
    model_size: 170,
    mmlu_score: 86.5,
    mt_bench_score: 8.99,
    big_bench_score: 40,
    input_cost: 30,
    output_cost: 60,
    rate_limit: 500,
    multilingual: 1,
    streaming_support: 1,
    function_call: 1,
    weight: 0.5,
  },
  {
    name: "GPT-3.5-turbo (Azure)",
    value: "azure/gpt-35-turbo",
    brand: "azure",
    icon: null,
    speed: 150,
    max_context_window: 4096,
    model_size: 20,
    mmlu_score: 70,
    mt_bench_score: 7.94,
    big_bench_score: 25,
    input_cost: 0.5,
    output_cost: 0.1,
    rate_limit: 30000,
    multilingual: 1,
    streaming_support: 1,
    function_call: 1,
    weight: 1,
  },
  {
    name: "GPT-4-32k (Azure)",
    value: "azure/gpt-4-32k",
    brand: "azure",
    icon: null,
    speed: 48,
    max_context_window: 32768,
    model_size: 170,
    mmlu_score: 86.5,
    mt_bench_score: 8.99,
    big_bench_score: 40,
    input_cost: 30,
    output_cost: 60,
    rate_limit: 500,
    multilingual: 1,
    streaming_support: 1,
    function_call: 1,
    weight: 0.5,
  },
];
