import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavigationLayout } from "@/layouts/NavigationLayout";
import { PostHogProvider } from './providers'
import dynamic from "next/dynamic";
import Head from "next/head";
// const inter = Inter({
//   subsets: ['latin'],
//   display: 'swap',
//   preload: true,
//   variable: '--font-inter',
// })

import Script from "next/script";



const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Keywords AI | #1 LLM Monitoring Platform for AI Startups",
  description:
    "Keywords AI: The leading LLM monitoring platform for AI startups. Easily monitor and improve your LLM applications with just 2 lines of code. Boost performance now.",
  icons: "https://www.keywordsai.co/logo.svg",
  openGraph: {
    type: "website",
    title: "Keywords AI - Build better AI products with complete observability",
    description:
      "Keywords AI is the best LLM monitoring platform for AI startups, you can easily monitor and improve your LLM appications with 2 lines of code.",
    url: "https://keywordsai.co",
    siteName: "Keywords AI",
    images: [
      {
        url: "https://keywordsai-static.s3.amazonaws.com/social_media_images/social_image.png",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    site: "@keywordsai",
    title: "Keywords AI",
    images: [
      "https://keywordsai-static.s3.amazonaws.com/social_media_images/social_image.png",
    ],
  },
};

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en" className={`${inter.variable} font-sans`}>
    <html lang="en" className={`${inter.variable}`}>
      <Script
        id="octolane-script"
        src="https://cdn.octolane.com/tag.js?pk=cccfe315250db4ca1c81"
        integrity="sha384-XPT8q+NKjJxHQpRdXyP/4m1Y5PU0xM19Plbth0o6ngMt6qZutj+gifGISAv1hORr"
        crossOrigin="anonymous"
      />
      <Script id="vector-script" strategy="afterInteractive">
        {`
          !function(e,r){try{if(e.vector)return void console.log("Vector snippet included more than once.");var t={};t.q=t.q||[];for(var o=["load","identify","on"],n=function(e){return function(){var r=Array.prototype.slice.call(arguments);t.q.push([e,r])}},c=0;c<o.length;c++){var a=o[c];t[a]=n(a)}if(e.vector=t,!t.loaded){var i=r.createElement("script");i.type="text/javascript",i.async=!0,i.src="https://cdn.vector.co/pixel.js";var l=r.getElementsByTagName("script")[0];l.parentNode.insertBefore(i,l),t.loaded=!0}}catch(e){console.error("Error loading Vector:",e)}}(window,document);
          vector.load("0f0ddc2f-310c-4e72-8c15-ee5b54dc5aca");
        `}
      </Script>
      <Head>
        <link rel="icon" href="/logo.svg" type="image/svg" sizes="26x26" />
        <Head>
          <link rel="icon" href="/icon.svg" type="image/svg" sizes="26x26" />
        </Head>
      </Head>
        <body>
          {/* <body> */}
          <PostHogProvider>
            <div className="bg-gray-black h-full w-full">
              <NavigationLayout>{children}</NavigationLayout>
            </div>
          </PostHogProvider>
        </body>
    </html>
  );
}

// import { PostHogProvider } from 'posthog-js/react';
// import posthog from 'posthog-js';
// import { NavigationLayout } from  '@/layouts/NavigationLayout';
// import { useEffect, useState } from 'react';

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   const [isMobile, setIsMobile] = useState(false)

//   useEffect(() => {
//     posthog.init("phc_rL8MrmFrie28wgxtDurKt9t1bwCzChaJQ7WYaj1F1gH", {
//       api_host: "https://app.posthog.com",
//     })

//     const script = document.createElement("script")
//     script.src = "https://cdn.octolane.com/tag.js?pk=cccfe315250db4ca1c81"
//     script.id = "octolane-script"
//     script.async = true
//     document.body.appendChild(script)

//     // Add mobile detection logic here
//     const handleResize = () => setIsMobile(window.innerWidth < 768)
//     window.addEventListener('resize', handleResize)
//     handleResize()

//     return () => {
//       document.body.removeChild(script)
//       window.removeEventListener('resize', handleResize)
//     }
//   }, [])

//   return (
//     <html lang="en">
//       <body>
//         <PostHogProvider client={posthog}>
//             <div className="bg-gray-black h-full w-full">
//               <NavigationLayout mobile={isMobile}>
//                 {children}
//               </NavigationLayout>
//             </div>
//         </PostHogProvider>
//       </body>
//     </html>
//   )
// }
